title :: "ray window";

width :: 1280;
height :: 720;

fps :: 60;

BACKGROUND_COLOR :: Color.{r = 0x2B, g = 0x2B, b = 0x2B, a = 0xFF};
FOREGROUND_COLOR :: Color.{r = 0xFF, g = 0x50, b = 0x50, a = 0xFF};
ANCHOR_COLOR :: Color.{r = 0x50, g = 0x50, b = 0xFF, a = 0xFF};
ROPE_COLOR :: Color.{r = 0xFF, g = 0xFF, b = 0xFF, a = 0xFF};

radius :: 50;
rope_thickness :: 10;

FullscreenKey :: 300; // F11
Q_Key :: 81;
