title :: "Hello, Sailor";

window_factor :: 100;
width :: 16*window_factor;
height :: 9*window_factor;

fps :: 60;

BACKGROUND_COLOR :: Color.{r = 0x00, g = 0x00, b = 0x00, a = 0xFF};
FOREGROUND_COLOR :: Color.{r = 0xFF, g = 0x50, b = 0x50, a = 0xFF};
WHITE :: Color.{r = 0xFF, g = 0xFF, b = 0xFF, a = 0xFF};

DEBUG :: true;

F11 :: 300; // F11
Q_Key :: 81;
W_Key :: 87;
A_Key :: 65;
S_Key :: 83;
D_Key :: 68;
